### ISSUE TITLE
Could you release the path of 'best-encoder-parameters.pt'?

### ISSUE THREAD

**Issue by xyxxmb** [DFGANDP/StyleGan2Parents_to_child#1]
And could you provide the download path of the file: 'age.npy'?

**Comment by xyxxmb** [comment]
And the download of file: 'age.npy'

**Comment by DFGANDP** [comment]
Hi,
encoder - https://drive.google.com/file/d/1-2cDi2DnN1UpZvxYZefgBTdoTfWk8uwX/view?usp=sharing
age vector - https://drive.google.com/file/d/106Thy5US6WjIadlNgiifIr9uKQ-jE6_Z/view?usp=sharing
Keep in mind about encoder was not trained properly.
Encoder repo - https://github.com/DFGANDP/StyleGan2-Ada_Encoder_projector
I forgot to add perceptual loss (Loss was only MSE, ppl need to be added), so results can be better :)

**Comment by xyxxmb** [comment]
Thank you
